export interface EmojiEntry {
  char: string;
  name: string;
  category: string;
  keywords: string[];
}

function entry(char: string, name: string, category: string, keywords: string[] = []): EmojiEntry {
  return { char, name, category, keywords: keywords.length > 0 ? keywords : [name] };
}

export const EMOJI_CATEGORIES = [
  "Smileys",
  "Gestures",
  "People",
  "Animals",
  "Food",
  "Activity",
  "Travel",
  "Objects",
  "Symbols",
  "Flags",
] as const;

/* -------------------------------- smileys -------------------------------- */

const SMILEYS: EmojiEntry[] = [
  entry("\u{1F600}", "grinning", "Smileys", ["smile", "happy", "face"]),
  entry("\u{1F603}", "smiley", "Smileys", ["happy", "face", " grin"]),
  entry("\u{1F604}", "smile", "Smileys", ["happy", "face", " teeth"]),
  entry("\u{1F601}", "grin", "Smileys", ["happy", "face", "big"]),
  entry("\u{1F606}", "laughing", "Smileys", ["haha", "lol", "face"]),
  entry("\u{1F605}", "sweat_smile", "Smileys", ["hot", "face", " relief"]),
  entry("\u{1F923}", "rofl", "Smileys", ["rolling", "laugh", "lol", "face"]),
  entry("\u{1F602}", "joy", "Smileys", ["tears", "laugh", "face"]),
  entry("\u{1F642}", "slightly_smiling_face", "Smileys", ["smile", "face"]),
  entry("\u{1F643}", "upside_down_face", "Smileys", ["sarcasm", "irony", "face"]),
  entry("\u{1FAE0}", "melting_face", "Smileys", ["hot", "drip", "face"]),
  entry("\u{1F609}", "wink", "Smileys", ["face", " flirt"]),
  entry("\u{1F60A}", "blush", "Smileys", ["shy", "face", " cute"]),
  entry("\u{1F607}", "smiling_imp", "Smileys", ["devil", "mischief", "face"]),
  entry("\u{1F970}", "smiling_face_with_three_hearts", "Smileys", ["love", "face", " adore"]),
  entry("\u{1F60D}", "heart_eyes", "Smileys", ["love", "crush", "face"]),
  entry("\u{1F929}", "star_struck", "Smileys", ["wow", "amazed", "face"]),
  entry("\u{1F618}", "kissing_heart", "Smileys", ["love", "face", " kiss"]),
  entry("\u{1F617}", "kissing", "Smileys", ["kiss", "face"]),
  entry("\u{1F61A}", "kissing_closed_eyes", "Smileys", ["kiss", "face", " love"]),
  entry("\u{1F619}", "kissing_smiling_eyes", "Smileys", ["kiss", "face", " love"]),
  entry("\u{1F60B}", "yum", "Smileys", ["tasty", "delicious", "face"]),
  entry("\u{1F61B}", "stuck_out_tongue", "Smileys", ["tongue", "playful", "face"]),
  entry("\u{1F61C}", "stuck_out_tongue_winking_eye", "Smileys", ["tongue", "joke", "face"]),
  entry("\u{1F92A}", "zany_face", "Smileys", ["crazy", "goofy", "face"]),
  entry("\u{1F61F}", "hugging_face", "Smileys", ["hug", "warm", "face"]),
  entry("\u{1F972}", "smiling_face_with_tear", "Smileys", ["upset", "relieved", "face"]),
  entry("\u{1F60F}", "smirking_face", "Smileys", ["smug", "face"]),
  entry("\u{1F612}", "unamused", "Smileys", ["deadpan", "annoyed", "face"]),
  entry("\u{1F644}", "face_with_rolling_eyes", "Smileys", ["eyeroll", "ugh", "face"]),
  entry("\u{1F62C}", "grimacing", "Smileys", ["awkward", "eek", "face"]),
  entry("\u{1F925}", "lying_face", "Smileys", ["pinocchio", "liar", "face"]),
  entry("\u{1F60C}", "relieved", "Smileys", ["calm", "phew", "face"]),
  entry("\u{1F614}", "pensive", "Smileys", ["sad", "thoughtful", "face"]),
  entry("\u{1F62A}", "sleepy", "Smileys", ["tired", "drowsy", "face"]),
  entry("\u{1F924}", "drooling_face", "Smileys", ["hungry", "want", "face"]),
  entry("\u{1F634}", "sleeping", "Smileys", ["zzz", "asleep", "face"]),
  entry("\u{1F637}", "mask", "Smileys", ["sick", "ill", "face"]),
  entry("\u{1F912}", "face_with_thermometer", "Smileys", ["sick", "fever", "face"]),
  entry("\u{1F915}", "face_with_head_bandage", "Smileys", ["hurt", "injured", "face"]),
  entry("\u{1F922}", "nauseated_face", "Smileys", ["sick", "gross", "face"]),
  entry("\u{1F92E}", "face_vomiting", "Smileys", ["sick", "puke", "face"]),
  entry("\u{1F927}", "sneezing_face", "Smileys", ["achoo", "sick", "face"]),
  entry("\u{1F975}", "hot_face", "Smileys", ["heat", "sweltering", "face"]),
  entry("\u{1F976}", "cold_face", "Smileys", ["freezing", "chilly", "face"]),
  entry("\u{1F974}", "woozy_face", "Smileys", ["drunk", "woozy", "face"]),
  entry("\u{1F635}", "dizzy_face", "Smileys", ["knocked", "confused", "face"]),
  entry("\u{1F92F}", "exploding_head", "Smileys", ["mind blown", "wow", "face"]),
  entry("\u{1F920}", "cowboy_hat_face", "Smileys", ["cowboy", "hat", "face"]),
  entry("\u{1F973}", "partying_face", "Smileys", ["celebrate", "party", "face"]),
  entry("\u{1F60E}", "smiling_face_with_sunglasses", "Smileys", ["cool", "sunglasses", "face"]),
  entry("\u{1F913}", "nerd_face", "Smileys", ["geek", "glasses", "face"]),
  entry("\u{1F9D0}", "face_with_monocle", "Smileys", ["fancy", "inspect", "face"]),
  entry("\u{1F615}", "confused", "Smileys", ["huh", "puzzled", "face"]),
  entry("\u{1F61F}", "hugs", "Smileys"),
  entry("\u{1F633}", "flushed", "Smileys", ["blush", "red", "face"]),
  entry("\u{1F97A}", "pleading_face", "Smileys", ["puppy eyes", "beg", "face"]),
  entry("\u{1F626}", "frowning_face", "Smileys", ["frown", "upset", "face"]),
  entry("\u{1F627}", "anguished", "Smileys", ["anguish", "pain", "face"]),
  entry("\u{1F628}", "fearful", "Smileys", ["scared", "afraid", "face"]),
  entry("\u{1F630}", "cold_sweat", "Smileys", ["nervous", "scared", "face"]),
  entry("\u{1F625}", "sad", "Smileys", ["frown", "cry", "face"]),
  entry("\u{1F622}", "cry", "Smileys", ["tears", "sad", "face"]),
  entry("\u{1F62D}", "loudly_crying_face", "Smileys", ["sob", "bawling", "face"]),
  entry("\u{1F631}", "scream", "Smileys", ["fear", "shock", "face"]),
  entry("\u{1F616}", "confounded", "Smileys", ["frustrated", "aggravated", "face"]),
  entry("\u{1F623}", "persevere", "Smileys", ["struggle", "determined", "face"]),
  entry("\u{1F61E}", "disappointed", "Smileys", ["sad", "down", "face"]),
  entry("\u{1F613}", "sweat", "Smileys", ["nervous", "phew", "face"]),
  entry("\u{1F629}", "weary", "Smileys", ["tired", "exhausted", "face"]),
  entry("\u{1F62B}", "tired_face", "Smileys", ["exhausted", "fed up", "face"]),
  entry("\u{1F624}", "triumph", "Smileys", ["huff", "smug", "face"]),
  entry("\u{1F621}", "rage", "Smileys", ["pissed", "angry", "face"]),
  entry("\u{1F620}", "angry", "Smileys", ["mad", "annoyed", "face"]),
  entry("\u{1F92C}", "cursing_face", "Smileys", ["swear", "angry", "face"]),
  entry("\u{1F608}", "smiling_face_with_horns", "Smileys", ["devil", "imp", "face"]),
  entry("\u{1F47F}", "imp", "Smileys", ["devil", "horns"]),
  entry("\u{1F480}", "skull", "Smileys", ["dead", "death", "bones"]),
  entry("\u{2620}", "skull_and_crossbones", "Smileys", ["dead", "danger", "bones"]),
  entry("\u{1F4A9}", "poop", "Smileys", ["pile", "turd", "shit"]),
  entry("\u{1F921}", "clown_face", "Smileys", ["clown", "circus", "face"]),
  entry("\u{1F479}", "ogre", "Smileys", ["monster", "japanese", "face"]),
  entry("\u{1F47A}", "goblin", "Smileys", ["monster", "japanese", "face"]),
  entry("\u{1F47B}", "ghost", "Smileys", ["halloween", "spooky", "boo"]),
  entry("\u{1F47D}", "alien", "Smileys", ["ufo", "space", "extraterrestrial"]),
  entry("\u{1F916}", "robot", "Smileys", ["bot", "machine", "android"]),
  entry("\u{1F63A}", "grinning_cat", "Smileys", ["cat", "smile", "happy"]),
  entry("\u{1F638}", "grinning_cat_with_wide_eyes", "Smileys", ["cat", "smile", "happy"]),
  entry("\u{1F639}", "cat_with_tears_of_joy", "Smileys", ["cat", "laugh", "lol"]),
  entry("\u{1F63B}", "smiling_cat_with_heart_eyes", "Smileys", ["cat", "love", "kiss"]),
  entry("\u{1F63C}", "cat_with_wry_smile", "Smileys", ["cat", "smile", "ironic"]),
  entry("\u{1F63D}", "kissing_cat", "Smileys", ["cat", "kiss", "love"]),
  entry("\u{1F640}", "weary_cat", "Smileys", ["cat", "tired", "unamused"]),
  entry("\u{1F63F}", "crying_cat", "Smileys", ["cat", "cry", "sad"]),
  entry("\u{1F63E}", "pouting_cat", "Smileys", ["cat", "angry", "grumpy"]),
  entry("\u{1F648}", "see_no_evil_monkey", "Smileys", ["monkey", "hide", "haha"]),
  entry("\u{1F649}", "hear_no_evil_monkey", "Smileys", ["monkey", "ears", "haha"]),
  entry("\u{1F64A}", "speak_no_evil_monkey", "Smileys", ["monkey", "hush", "haha"]),
  entry("\u{1F48B}", "kiss_mark", "Smileys", ["lipstick", "beauty", "kiss"]),
  entry("\u{1F48C}", "couple_with_heart", "Smileys", ["love", "relationship"]),
  entry("\u{1F498}", "coupleheart", "Smileys", ["love", "relationship", " pink"]),
  entry("\u{1F49D}", "heart_with_ribbon", "Smileys", ["love", "gift", "valentine"]),
  entry("\u{1F49E}", "revolving_hearts", "Smileys", ["love", "affection"]),
  entry("\u{1F49C}", "heart_decoration", "Smileys", ["love", "affection", " purple"]),
  entry("\u{1F5A4}", "black_heart", "Smileys", ["love", "dark"]),
  entry("\u{2764}\u{FE0F}", "heart", "Smileys", ["love", "red"]),
  entry("\u{1F9E1}", "orange_heart", "Smileys", ["love", "orange"]),
  entry("\u{1F49B}", "yellow_heart", "Smileys", ["love", "yellow"]),
  entry("\u{1F49A}", "green_heart", "Smileys", ["love", "green"]),
  entry("\u{1F499}", "blue_heart", "Smileys", ["love", "blue"]),
  entry("\u{1FA75}", "light_blue_heart", "Smileys", ["love", "cyan"]),
  entry("\u{1F49C}", "purple_heart", "Smileys", ["love", "purple"]),
  entry("\u{1F90E}", "brown_heart", "Smileys", ["love", "brown"]),
  entry("\u{1F90D}", "white_heart", "Smileys", ["love", "white"]),
  entry("\u{1F494}", "broken_heart", "Smileys", ["sad", "heartbreak"]),
  entry("\u{2763}\u{FE0F}", "heart_exclamation", "Smileys", ["love", "decoration"]),
  entry("\u{1F495}", "two_hearts", "Smileys", ["love", "affection", " purple"]),
  entry("\u{1F496}", "sparkling_heart", "Smileys", ["love", "shiny", "affection"]),
  entry("\u{1F497}", "growing_heart", "Smileys", ["love", "affection"]),
  entry("\u{1F4AF}", "hundred", "Smileys", ["100", "score", "perfect"]),
  entry("\u{1F4A2}", "anger", "Smileys", ["angry", "mad"]),
  entry("\u{1F4A5}", "boom", "Smileys", ["collision", "explosion", "anger"]),
  entry("\u{1F4AB}", "dizzy", "Smileys", ["star", "shoot", "sparkle"]),
  entry("\u{1F4A6}", "sweat_drops", "Smileys", ["water", "splashed"]),
  entry("\u{1F4A8}", "dashing_away", "Smileys", ["fast", "run", "wind"]),
  entry("\u{1F573}", "hole", "Smileys", ["circle", "spot"]),
  entry("\u{1F4AC}", "speech_balloon", "Smileys", ["comment", "talk", " message"]),
  entry("\u{1F441}\u{FE0F}", "eyes", "Smileys", ["look", "watch", "see"]),
  entry("\u{1F440}", "eyes", "Smileys", ["look", "watch", "see"]),
  entry("\u{1F445}", "tongue", "Smileys", ["taste", "lick"]),
  entry("\u{1F444}", "mouth", "Smileys", ["eat", "kiss", "yum"]),
  entry("\u{1FAE6}", "face_with_open_eyes_and_hand_over_mouth", "Smileys", ["oops", "gossip", " face"]),
  entry("\u{1FAE7}", "face_with_peeking_eye", "Smileys", ["peek", "watch", " face"]),
  entry("\u{1F92D}", "hand_over_mouth", "Smileys", ["oops", "silence", " face"]),
  entry("\u{1FAE3}", "melting", "Smileys", ["drip", "hot", " face"]),
  entry("\u{1F636}", "no_mouth", "Smileys", ["silent", "quiet", "face"]),
  entry("\u{1F60F}\u{FE0F}", "smirk", "Smileys", ["smug", "face"]),
];

/* ------------------------------- gestures -------------------------------- */

const GESTURES: EmojiEntry[] = [
  entry("\u{1F44B}", "wave", "Gestures", ["hello", "hi", "bye", "hand"]),
  entry("\u{1F91A}", "raised_back_of_hand", "Gestures", ["hand", "palm"]),
  entry("\u{1F590}\u{FE0F}", "hand_with_fingers_splayed", "Gestures", ["hand", "fingers", "spread"]),
  entry("\u{270B}", "raised_hand", "Gestures", ["stop", "hand", "high five"]),
  entry("\u{1F596}", "vulcan_salute", "Gestures", ["spock", "star trek", "hand"]),
  entry("\u{1FAF1}", "rightwards_hand", "Gestures", ["point", "direction"]),
  entry("\u{1FAF2}", "leftwards_hand", "Gestures", ["point", "direction"]),
  entry("\u{1FAF3}", "palm_down_hand", "Gestures", ["calm", "low", "hand"]),
  entry("\u{1FAF4}", "palm_up_hand", "Gestures", ["joker", "money", "hand"]),
  entry("\u{1F44C}", "ok_hand", "Gestures", ["okay", "perfect", "hand"]),
  entry("\u{270C}", "v", "Gestures", ["peace", "victory", "two"]),
  entry("\u{1F91E}", "crossed_fingers", "Gestures", ["luck", "hope", "hand"]),
  entry("\u{1F91F}", "love_you_gesture", "Gestures", ["ily", "hand"]),
  entry("\u{1F918}", "sign_of_the_horns", "Gestures", ["rock", "metal", "hand"]),
  entry("\u{1F919}", "call_me_hand", "Gestures", ["shaka", "phone", "hand"]),
  entry("\u{1F448}", "point_left", "Gestures", ["direction", "finger"]),
  entry("\u{1F449}", "point_right", "Gestures", ["direction", "finger"]),
  entry("\u{1F446}", "point_up_2", "Gestures", ["direction", "finger", " two"]),
  entry("\u{1F447}", "point_down", "Gestures", ["direction", "finger"]),
  entry("\u{1FAF5}", "index_pointing_at_the_viewer", "Gestures", ["point", "you"]),
  entry("\u{1F44D}", "thumbsup", "Gestures", ["like", "yes", "approve", "hand"]),
  entry("\u{1F44E}", "thumbsdown", "Gestures", ["dislike", "no", "hand"]),
  entry("\u{1F44F}", "clap", "Gestures", ["applause", "praise", "hands"]),
  entry("\u{1F64C}", "raising_hands", "Gestures", ["celebrate", "praise", "hooray"]),
  entry("\u{1F450}", "open_hands", "Gestures", ["hug", "jazz", "hands"]),
  entry("\u{1F932}", "palms_up_together", "Gestures", ["praise", "pray", " hands"]),
  entry("\u{1F91D}", "handshake", "Gestures", ["deal", "agreement", "shake"]),
  entry("\u{1F64F}", "folded_hands", "Gestures", ["pray", "thanks", "please", "please"]),
  entry("\u{1F4AA}", "muscle", "Gestures", ["strong", "flex", "arm"]),
  entry("\u{1F4A3}", "bomb", "Gestures", ["explode", "fire"]),
  entry("\u{1F44A}", "punch", "Gestures", ["fist", "fist bump"]),
  entry("\u{1F91B}", "left_facing_fist", "Gestures", ["fist", "punch"]),
  entry("\u{1F91C}", "right_facing_fist", "Gestures", ["fist", "punch"]),
  entry("\u{1F44B}\u{FE0F}", "wave", "Gestures", ["hello", "bye"]),
  entry("\u{1F91A}\u{FE0F}", "raised_back_of_hand", "Gestures", ["hand"]),
  entry("\u{1F595}", "middle_finger", "Gestures", ["flipping", "rude", "hand"]),
  entry("\u{1F918}\u{FE0F}", "metal", "Gestures", ["rock", "hand"]),
  entry("\u{1F926}", "facepalm", "Gestures", ["disbelief", "hand", " face"]),
  entry("\u{1FAF6}", "handshake", "Gestures", ["deal"]),
  entry("\u{1FAE2}", "hand_with_index_finger_and_thumb_crossed", "Gestures", ["heart", "love", "hand"]),
  entry("\u{1FAF7}", "leftwards_pushing_hand", "Gestures", ["push", "stop", "hand"]),
  entry("\u{1FAF8}", "rightwards_pushing_hand", "Gestures", ["push", "stop", "hand"]),
  entry("\u{1F44A}\u{FE0F}", "oncoming_fist", "Gestures", ["punch", "fist"]),
];

/* -------------------------------- people --------------------------------- */

const PEOPLE: EmojiEntry[] = [
  entry("\u{1F468}", "man", "People", ["adult", "male"]),
  entry("\u{1F469}", "woman", "People", ["adult", "female"]),
  entry("\u{1F9D1}", "person", "People", ["adult", "neutral"]),
  entry("\u{1F466}", "boy", "People", ["child", "young", "male"]),
  entry("\u{1F467}", "girl", "People", ["child", "young", "female"]),
  entry("\u{1F9D2}", "child", "People", ["young", "neutral"]),
  entry("\u{1F476}", "baby", "People", ["child", "infant"]),
  entry("\u{1F9D3}", "older_person", "People", ["elderly", "old"]),
  entry("\u{1F474}", "old_man", "People", ["elderly", "grandpa"]),
  entry("\u{1F475}", "old_woman", "People", ["elderly", "grandma"]),
  entry("\u{1F46A}", "family", "People", ["parents", "group"]),
  entry("\u{1F468}\u{200D}\u{1F469}\u{200D}\u{1F466}", "family_man_woman_boy", "People", ["parents", "group"]),
  entry("\u{1F469}\u{200D}\u{1F4BB}", "woman_technologist", "People", ["developer", "coding", "female"]),
  entry("\u{1F468}\u{200D}\u{1F4BB}", "man_technologist", "People", ["developer", "coding", "male"]),
  entry("\u{1F9D9}", "person_technologist", "People", ["developer", "coding"]),
  entry("\u{1F9D8}", "person_in_tuxedo", "People", ["formal", "suit"]),
  entry("\u{1F935}", "person_in_tuxedo", "People", ["formal", "suit"]),
  entry("\u{1F470}", "person_with_veil", "People", ["wedding", "bride", "formal"]),
  entry("\u{1F930}", "pregnant_woman", "People", ["expecting", "baby"]),
  entry("\u{1F931}", "breast_feeding", "People", ["baby", "feeding"]),
  entry("\u{1F47C}", "baby_angel", "People", ["cherub", "cupid", "wing"]),
  entry("\u{1F385}", "santa", "People", ["christmas", "xmas", "father"]),
  entry("\u{1F936}", "ms_claus", "People", ["christmas", "mother"]),
  entry("\u{1F9B8}", "superhero", "People", ["hero", "cape", "mask"]),
  entry("\u{1F9B9}", "supervillain", "People", ["villain", "cape", "mask"]),
  entry("\u{1F9D9}\u{200D}\u{1F680}", "astronaut", "People", ["space", "nasa"]),
  entry("\u{1F680}", "rocket", "People", ["space", "launch", "ship"]),
  entry("\u{1F575}\u{FE0F}", "detective", "People", ["spy", "sherlock"]),
  entry("\u{1F46E}", "police_officer", "People", ["cop", "law", "male"]),
  entry("\u{1F477}", "construction_worker", "People", ["builder", "work"]),
  entry("\u{1F482}", "guard", "People", ["security", "work"]),
  entry("\u{1F977}", "ninja", "People", ["martial arts", "stealth"]),
  entry("\u{1F9D8}\u{200D}\u{2695}\u{FE0F}", "health_worker", "People", ["doctor", "nurse", "medical"]),
  entry("\u{1F9D9}\u{200D}\u{2695}\u{FE0F}", "person_health_worker", "People", ["doctor", "nurse"]),
  entry("\u{1F9D1}\u{200D}\u{1F91D}", "people_holding_hands", "People", ["couple", "friends"]),
  entry("\u{1F46B}", "woman_and_man_holding_hands", "People", ["couple", "relationship"]),
  entry("\u{1F46C}", "men_holding_hands", "People", ["couple", "friends"]),
  entry("\u{1F46D}", "women_holding_hands", "People", ["couple", "friends"]),
  entry("\u{1F9D1}", "adult", "People", ["grown", "neutral"]),
  entry("\u{1F464}", "bust_in_silhouette", "People", ["anonymous", "unknown", "user"]),
  entry("\u{1F465}", "busts_in_silhouette", "People", ["anonymous", "unknown", "users"]),
  entry("\u{1F463}", "footprints", "People", ["steps", "walk"]),
  entry("\u{1F9D4}", "person_bald", "People", ["hair", "bald"]),
  entry("\u{1F9D3}\u{200D}\u{1F33E}", "farmer", "People", ["work", "agriculture"]),
  entry("\u{1F474}\u{200D}\u{1F525}", "old_man_white_hair", "People", ["elderly"]),
  entry("\u{1F9D7}", "person_climbing", "People", ["climb", "sport"]),
  entry("\u{1F93A}", "person_fencing", "People", ["sport", "fencing"]),
  entry("\u{1F3C3}", "person_running", "People", ["sport", "run", "marathon"]),
  entry("\u{26F9}", "person_bouncing_ball", "People", ["sport", "basketball"]),
  entry("\u{1F3CB}", "person_lifting_weights", "People", ["sport", "gym", "workout"]),
  entry("\u{1F6B6}", "person_walking", "People", ["stroll", "walk"]),
];

/* ------------------------------- animals --------------------------------- */

const ANIMALS: EmojiEntry[] = [
  entry("\u{1F435}", "monkey_face", "Animals", ["ape", "monkey"]),
  entry("\u{1F412}", "monkey", "Animals", ["ape"]),
  entry("\u{1F98D}", "gorilla", "Animals", ["ape", "strong"]),
  entry("\u{1F415}", "dog", "Animals", ["puppy", "pet"]),
  entry("\u{1F436}", "dog_face", "Animals", ["puppy", "pet"]),
  entry("\u{1F429}", "poodle", "Animals", ["dog", "pet"]),
  entry("\u{1F98A}", "fox", "Animals", ["animal"]),
  entry("\u{1F99D}", "raccoon", "Animals", ["animal"]),
  entry("\u{1F431}", "cat_face", "Animals", ["kitten", "pet"]),
  entry("\u{1F408}", "cat", "Animals", ["kitten", "pet"]),
  entry("\u{1F408}\u{200D}\u{2B1B}", "black_cat", "Animals", ["cat", "luck", "lunar"]),
  entry("\u{1F981}", "lion", "Animals", ["cat", "king"]),
  entry("\u{1F42F}", "tiger_face", "Animals", ["big cat"]),
  entry("\u{1F405}", "tiger2", "Animals", ["big cat"]),
  entry("\u{1F406}", "leopard", "Animals", ["big cat"]),
  entry("\u{1F434}", "horse", "Animals", ["pony"]),
  entry("\u{1FACE}", "moose", "Animals", ["deer"]),
  entry("\u{1FAC}", "goose", "Animals", ["bird", "duck"]),
  entry("\u{1F985}", "eagle", "Animals", ["bird", "fly"]),
  entry("\u{1F989}", "owl", "Animals", ["bird", "night"]),
  entry("\u{1F438}", "frog", "Animals", ["toad", "ribbit"]),
  entry("\u{1F40A}", "crocodile", "Animals", ["reptile", "alligator"]),
  entry("\u{1F422}", "turtle", "Animals", ["slow", "tortoise"]),
  entry("\u{1F98E}", "lizard", "Animals", ["gecko", "reptile"]),
  entry("\u{1F40D}", "snake", "Animals", ["serpent", "reptile"]),
  entry("\u{1F433}", "spouting_whale", "Animals", ["ocean"]),
  entry("\u{1F42C}", "dolphin", "Animals", ["ocean", "sea"]),
  entry("\u{1F41F}", "fish", "Animals", ["ocean", "sea"]),
  entry("\u{1F420}", "tropical_fish", "Animals", ["ocean", "reef"]),
  entry("\u{1F42C}\u{200D}\u{1F4A8}", "dolphin_fin", "Animals", ["ocean"]),
  entry("\u{1F990}", "shrimp", "Animals", ["prawn", "ocean"]),
  entry("\u{1F421}", "blowfish", "Animals", ["pufferfish", "ocean"]),
  entry("\u{1F988}", "shark", "Animals", ["ocean"]),
  entry("\u{1F419}", "octopus", "Animals", ["tentacles", "ocean"]),
  entry("\u{1F41A}", "spiral_shell", "Animals", ["ocean", "beach"]),
  entry("\u{1FAB8}", "beaver", "Animals", ["dam"]),
  entry("\u{1FAB6}", "feather", "Animals", ["bird", "quill"]),
  entry("\u{1F426}", "bird", "Animals", ["tweet", "fly"]),
  entry("\u{1F427}", "penguin", "Animals", ["bird", "antarctica"]),
  entry("\u{1F54A}", "dove", "Animals", ["peace", "bird"]),
  entry("\u{1F985}\u{FE0F}", "eagle", "Animals", ["bird"]),
  entry("\u{1F99A}", "peacock", "Animals", ["bird", "pride"]),
  entry("\u{1F438}", "frog", "Animals", ["toad"]),
  entry("\u{1F422}\u{FE0F}", "turtle", "Animals", ["tortoise"]),
  entry("\u{1F98B}", "butterfly", "Animals", ["insect", "wing"]),
  entry("\u{1F41B}", "bug", "Animals", ["insect", "beetle"]),
  entry("\u{1F41D}", "honeybee", "Animals", ["bee", "insect"]),
  entry("\u{1FAB2}", "beetle", "Animals", ["insect", "bug"]),
  entry("\u{1F98A}\u{FE0F}", "fox", "Animals", ["animal"]),
  entry("\u{1F41E}", "lady_beetle", "Animals", ["bug", "insect", "ladybug"]),
  entry("\u{1F577}\u{FE0F}", "spider", "Animals", ["web", "arachnid"]),
  entry("\u{1F578}\u{FE0F}", "spider_web", "Animals", ["web"]),
  entry("\u{1F400}", "rat", "Animals", ["rodent"]),
  entry("\u{1F439}", "hamster", "Animals", ["pet", "rodent"]),
  entry("\u{1F430}", "rabbit_face", "Animals", ["bunny", "pet"]),
  entry("\u{1F407}", "rabbit", "Animals", ["bunny", "pet"]),
  entry("\u{1F43F}", "chipmunk", "Animals", ["squirrel"]),
  entry("\u{1F9AB}", "beaver", "Animals", ["dam"]),
  entry("\u{1F994}", "hedgehog", "Animals", ["spiky", "cute"]),
  entry("\u{1F987}", "bat", "Animals", ["vampire", "night"]),
  entry("\u{1F43B}", "bear", "Animals", ["grizzly"]),
  entry("\u{1F43B}\u{FE0F}", "bear", "Animals", ["grizzly"]),
  entry("\u{1F428}", "koala", "Animals", ["australia", "cute"]),
  entry("\u{1F43C}", "panda", "Animals", ["bamboo", "cute"]),
  entry("\u{1F9A5}", "sloth", "Animals", ["slow"]),
  entry("\u{1F9A6}", "otter", "Animals", ["sea otter"]),
  entry("\u{1F995}", "sauropod", "Animals", ["dinosaur", "long"]),
  entry("\u{1F996}", "t_rex", "Animals", ["dinosaur", "trex"]),
  entry("\u{1F433}", "spouting_whale", "Animals", ["ocean"]),
  entry("\u{1F40F}", "crocodile", "Animals", ["reptile"]),
  entry("\u{1F335}", "cactus", "Animals", ["plant", "desert"]),
];

/* --------------------------------- food ---------------------------------- */

const FOOD: EmojiEntry[] = [
  entry("\u{1F34E}", "red_apple", "Food", ["fruit"]),
  entry("\u{1F34C}", "banana", "Food", ["fruit"]),
  entry("\u{1F349}", "grapes", "Food", ["fruit"]),
  entry("\u{1F34A}", "tangerine", "Food", ["orange", "fruit"]),
  entry("\u{1F34B}", "lemon", "Food", ["fruit"]),
  entry("\u{1F34D}", "banana", "Food", ["fruit"]),
  entry("\u{1F96D}", "mango", "Food", ["fruit"]),
  entry("\u{1F34E}", "apple", "Food", ["fruit"]),
  entry("\u{1F353}", "strawberry", "Food", ["fruit", "berry"]),
  entry("\u{1F95E}", "pancakes", "Food", ["breakfast", "syrup"]),
  entry("\u{1F950}", "croissant", "Food", ["bread", "france"]),
  entry("\u{1F35E}", "bread", "Food", ["loaf", "toast"]),
  entry("\u{1F9C0}", "cheese_wedge", "Food", ["dairy"]),
  entry("\u{1F356}", "meat_on_bone", "Food", ["meat", "drumstick"]),
  entry("\u{1F357}", "poultry_leg", "Food", ["meat", "chicken"]),
  entry("\u{1F969}", "cut_of_meat", "Food", ["meat", "steak"]),
  entry("\u{1F953}", "bacon", "Food", ["meat", "breakfast"]),
  entry("\u{1F354}", "hamburger", "Food", ["burger", "fast food"]),
  entry("\u{1F35F}", "french_fries", "Food", ["fries", "fast food"]),
  entry("\u{1F355}", "pizza", "Food", ["slice"]),
  entry("\u{1F32D}", "hot_dog", "Food", ["fast food"]),
  entry("\u{1F96A}", "sandwich", "Food", ["lunch"]),
  entry("\u{1F32E}", "taco", "Food", ["mexican"]),
  entry("\u{1F32F}", "burrito", "Food", ["mexican", "wrap"]),
  entry("\u{1F959}", "stuffed_flatbread", "Food", ["pita"]),
  entry("\u{1F9C6}", "falafel", "Food", ["chickpea"]),
  entry("\u{1F95A}", "egg", "Food", ["breakfast", "fried"]),
  entry("\u{1F373}", "cooking", "Food", ["egg", "fried", "breakfast"]),
  entry("\u{1F958}", "shallow_pan_of_food", "Food", ["egg", "cooking"]),
  entry("\u{1F372}", "pot_of_food", "Food", ["stew", "soup"]),
  entry("\u{1FAD5}", "fondue", "Food", ["cheese", "swiss"]),
  entry("\u{1F963}", "bowl_with_spoon", "Food", ["cereal", "porridge"]),
  entry("\u{1F957}", "green_salad", "Food", ["healthy", "lettuce"]),
  entry("\u{1F37F}", "popcorn", "Food", ["movie", "snack"]),
  entry("\u{1F9C2}", "salt", "Food", ["seasoning"]),
  entry("\u{1F96B}", "canned_food", "Food", ["soup", "tin"]),
  entry("\u{1F371}", "bento", "Food", ["japan", "lunch"]),
  entry("\u{1F358}", "rice_cracker", "Food", ["snack"]),
  entry("\u{1F359}", "rice_ball", "Food", ["onigiri", "japan"]),
  entry("\u{1F35A}", "cooked_rice", "Food", ["bowl", "rice"]),
  entry("\u{1F360}", "roasted_sweet_potato", "Food", ["yam", "side"]),
  entry("\u{1F362}", "oden", "Food", ["japan", "skewer"]),
  entry("\u{1F363}", "sushi", "Food", ["japan", "fish"]),
  entry("\u{1F364}", "fried_shrimp", "Food", ["japan", "tempura"]),
  entry("\u{1F95C}", "peanuts", "Food", ["nuts"]),
  entry("\u{1F36D}", "candy", "Food", ["sweet"]),
  entry("\u{1F36C}", "candy", "Food", ["sweet"]),
  entry("\u{1F36B}", "chocolate_bar", "Food", ["sweet"]),
  entry("\u{1F36A}", "cookie", "Food", ["biscuit", "sweet"]),
  entry("\u{1F369}", "doughnut", "Food", ["donut", "sweet"]),
  entry("\u{1F36F}", "honey_pot", "Food", ["sweet", "bee"]),
  entry("\u{1F9C1}", "shortcake", "Food", ["dessert", "cake"]),
  entry("\u{1F370}", "shortcake", "Food", ["cake", "dessert"]),
  entry("\u{1F9C0}", "cheese", "Food", ["dairy"]),
  entry("\u{1F95B}", "butter", "Food", ["dairy"]),
  entry("\u{1FAD2}", "cupcake", "Food", ["cake", "dessert"]),
  entry("\u{1F9C1}", "cake", "Food", ["dessert"]),
  entry("\u{1F967}", "pie", "Food", ["dessert"]),
  entry("\u{1F36F}", "honey", "Food", ["sweet"]),
  entry("\u{1F9C4}", "garlic", "Food", ["seasoning", "flavor"]),
  entry("\u{1F9C5}", "onion", "Food", ["vegetable"]),
  entry("\u{1F96C}\u{FE0F}", "leafy_green", "Food", ["vegetable"]),
  entry("\u{1F955}", "carrot", "Food", ["vegetable"]),
  entry("\u{1F33D}", "ear_of_corn", "Food", ["vegetable"]),
  entry("\u{1F336}\u{FE0F}", "hot_pepper", "Food", ["spicy", "chili"]),
  entry("\u{1F952}", "cucumber", "Food", ["vegetable", "pickle"]),
  entry("\u{1F966}", "broccoli", "Food", ["vegetable"]),
  entry("\u{1F9C4}\u{FE0F}", "garlic", "Food", ["seasoning"]),
  entry("\u{1F954}", "ginger", "Food", ["seasoning"]),
  entry("\u{1FAD1}", "ginger", "Food", ["spicy"]),
  entry("\u{1FAD4}\u{FE0F}", "beans", "Food", ["legume"]),
  entry("\u{1F35B}", "dango", "Food", ["japan", "sweet"]),
  entry("\u{1FAD9}\u{FE0F}", "tamale", "Food", ["mexican"]),
];

/* ------------------------------- activity -------------------------------- */

const ACTIVITY: EmojiEntry[] = [
  entry("\u{26BD}", "soccer", "Activity", ["football", "ball"]),
  entry("\u{26BE}", "baseball", "Activity", ["ball", "sport"]),
  entry("\u{1F94E}", "softball", "Activity", ["ball", "sport"]),
  entry("\u{1F3C0}", "basketball", "Activity", ["hoop", "sport"]),
  entry("\u{1F3C8}", "american_football", "Activity", ["nfl", "sport"]),
  entry("\u{1F3C1}", "flag_in_hole", "Activity", ["golf", "sport"]),
  entry("\u{26F3}", "golf", "Activity", ["sport", "flag"]),
  entry("\u{26F8}", "ice_skate", "Activity", ["skating", "sport"]),
  entry("\u{1F3A3}", "bowling", "Activity", ["sport", "strike"]),
  entry("\u{1F3CF}", "cricket_game", "Activity", ["bat", "sport"]),
  entry("\u{1F3D1}", "field_hockey", "Activity", ["sport"]),
  entry("\u{1F3D2}", "ice_hockey", "Activity", ["sport"]),
  entry("\u{1F94D}", "lacrosse", "Activity", ["sport"]),
  entry("\u{1F3D3}", "ping_pong", "Activity", ["table tennis", "sport"]),
  entry("\u{1F3F8}", "badminton", "Activity", ["sport"]),
  entry("\u{1F94B}", "boxing_glove", "Activity", ["fight", "sport"]),
  entry("\u{1F94A}", "martial_arts_uniform", "Activity", ["karate", "sport"]),
  entry("\u{1F3B8}", "guitar", "Activity", ["music", "instrument"]),
  entry("\u{1F3B9}", "musical_keyboard", "Activity", ["piano", "music"]),
  entry("\u{1F3BC}", "musical_score", "Activity", ["music", "sheet"]),
  entry("\u{1F3B5}", "musical_note", "Activity", ["music", "tune"]),
  entry("\u{1F3B6}", "musical_notes", "Activity", ["music", "tune"]),
  entry("\u{1F399}\u{FE0F}", "studio_microphone", "Activity", ["sing", "music", "record"]),
  entry("\u{1F3A4}", "microphone", "Activity", ["sing", "karaoke"]),
  entry("\u{1F3A7}", "headphone", "Activity", ["music", "listen"]),
  entry("\u{1F941}", "drum", "Activity", ["music", "beat"]),
  entry("\u{1F4F1}", "iphone", "Activity", ["phone", "mobile", "apple"]),
  entry("\u{260E}", "telephone", "Activity", ["phone", "call"]),
  entry("\u{1F4F2}", "mobile_phone", "Activity", ["cell", "smartphone"]),
  entry("\u{1F4BB}", "computer", "Activity", ["laptop", "code", "dev"]),
  entry("\u{2328}", "keyboard", "Activity", ["type", "input", "code"]),
  entry("\u{1F5A5}", "desktop_computer", "Activity", ["pc", "monitor"]),
  entry("\u{1F5A8}", "printer", "Activity", ["paper"]),
  entry("\u{1F4F7}", "camera", "Activity", ["photo", "picture"]),
  entry("\u{1F4F8}", "camera_flash", "Activity", ["photo"]),
  entry("\u{1F4F9}", "video_camera", "Activity", ["record", "film"]),
  entry("\u{1F4FC}", "vhs", "Activity", ["retro", "tape"]),
  entry("\u{1F50B}", "battery", "Activity", ["power", "charge"]),
  entry("\u{1F50C}", "electric_plug", "Activity", ["power"]),
  entry("\u{1F4DA}", "books", "Activity", ["library", "study"]),
  entry("\u{270D}", "writing_hand", "Activity", ["write", "pen"]),
  entry("\u{1F4DD}", "memo", "Activity", ["write", "note"]),
  entry("\u{1F4C8}", "chart_with_upwards_trend", "Activity", ["graph", "growth", "stats"]),
  entry("\u{1F4C9}", "chart_with_downwards_trend", "Activity", ["graph", "loss", "stats"]),
  entry("\u{1F4CA}", "bar_chart", "Activity", ["graph", "stats"]),
  entry("\u{1F3AE}", "video_game", "Activity", ["gaming", "controller"]),
  entry("\u{1F579}\u{FE0F}", "joystick", "Activity", ["gaming"]),
  entry("\u{1F3B2}", "game_die", "Activity", ["dice", "random", "rpg"]),
  entry("\u{265F}\u{FE0F}", "chess_pawn", "Activity", ["board game", "strategy"]),
  entry("\u{1FA84}", "mahjong", "Activity", ["tiles", "game"]),
  entry("\u{1F3AD}", "performing_arts", "Activity", ["theatre", "drama"]),
  entry("\u{1F3AA}", "circus_tent", "Activity", ["carnival", "show"]),
  entry("\u{1F3B8}\u{FE0F}", "guitar", "Activity", ["music"]),
  entry("\u{1F3B9}\u{FE0F}", "musical_keyboard", "Activity", ["piano"]),
  entry("\u{1F937}", "person_shrugging", "Activity", ["shrug", "dunno", " person"]),
  entry("\u{1F483}", "woman_dancing", "Activity", ["dance", "party"]),
  entry("\u{1F57A}", "man_dancing", "Activity", ["dance", "party"]),
  entry("\u{1F3F4}\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}", "black_flag", "Activity", ["gaming", "team"]),
  entry("\u{1F3F9}", "triangular_flag_on_post", "Activity", ["milestone"]),
  entry("\u{1F3C6}", "trophy", "Activity", ["win", "award"]),
  entry("\u{1F947}", "1st_place_medal", "Activity", ["gold", "winner"]),
  entry("\u{1F948}", "2nd_place_medal", "Activity", ["silver", "runner up"]),
  entry("\u{1F949}", "3rd_place_medal", "Activity", ["bronze"]),
  entry("\u{26BD}\u{FE0F}", "soccer", "Activity", ["football"]),
  entry("\u{1F3C5}", "sports_medal", "Activity", ["award", "winner"]),
  entry("\u{1F4A6}", "droplet", "Activity", ["water"]),
  entry("\u{1F3AF}", "bullseye", "Activity", ["target", "goal"]),
  entry("\u{1FA80}", "yo_yo", "Activity", ["toy"]),
];

/* -------------------------------- travel --------------------------------- */

const TRAVEL: EmojiEntry[] = [
  entry("\u{1F680}", "rocket", "Travel", ["launch", "space"]),
  entry("\u{2708}", "airplane", "Travel", ["flight", "travel"]),
  entry("\u{1F697}", "automobile", "Travel", ["car", "drive"]),
  entry("\u{1F699}", "sport_utility_vehicle", "Travel", ["car", "suv"]),
  entry("\u{1F6FB}", "pickup_truck", "Travel", ["car", "truck"]),
  entry("\u{1F69B}", "bus", "Travel", ["transit"]),
  entry("\u{1F68C}", "bus_stop", "Travel", ["transit", "wait"]),
  entry("\u{1F695}", "trolleybus", "Travel", ["transit"]),
  entry("\u{1F692}", "fire_engine", "Travel", ["truck", "emergency"]),
  entry("\u{1F691}", "ambulance", "Travel", ["emergency", "hospital"]),
  entry("\u{1F69A}", "police_car", "Travel", ["emergency", "cop"]),
  entry("\u{1F6B2}", "bicycle", "Travel", ["bike", "cycle"]),
  entry("\u{1F6F4}", "kick_scooter", "Travel", ["scooter"]),
  entry("\u{1F6F9}", "motor_scooter", "Travel", ["moped", "scooter"]),
  entry("\u{1F68C}", "bus", "Travel", ["transit"]),
  entry("\u{1F683}", "train", "Travel", ["rail", "subway"]),
  entry("\u{1F686}", "train2", "Travel", ["rail"]),
  entry("\u{1F68F}", "tram", "Travel", ["light rail"]),
  entry("\u{1F687}", "metro", "Travel", ["subway", "underground"]),
  entry("\u{1F684}", "bullettrain_side", "Travel", ["high speed", "train"]),
  entry("\u{1F685}", "bullettrain_front", "Travel", ["high speed", "train"]),
  entry("\u{1F689}", "station", "Travel", ["train", "platform"]),
  entry("\u{1F682}", "locomotive", "Travel", ["train"]),
  entry("\u{270D}\u{FE0F}", "ticket", "Travel", ["boarding"]),
  entry("\u{1F39F}\u{FE0F}", "tickets", "Travel", ["boarding pass"]),
  entry("\u{1F6A2}", "ship", "Travel", ["boat", "cruise"]),
  entry("\u{26F5}", "sailboat", "Travel", ["boat", "yacht"]),
  entry("\u{1F6A4}", "speedboat", "Travel", ["boat"]),
  entry("\u{1F6A3}", "ferry", "Travel", ["boat"]),
  entry("\u{26F4}", "anchor", "Travel", ["ship", "port"]),
  entry("\u{1F5FF}", "moai", "Travel", ["easter island"]),
  entry("\u{1F3D5}\u{FE0F}", "camping", "Travel", ["nature"]),
  entry("\u{1F3D6}\u{FE0F}", "beach_with_umbrella", "Travel", ["holiday", "sea"]),
  entry("\u{1F3DC}\u{FE0F}", "desert", "Travel", ["sand", "arid"]),
  entry("\u{1F3DD}\u{FE0F}", "desert_island", "Travel", ["palms"]),
  entry("\u{1F3DE}\u{FE0F}", "national_park", "Travel", ["nature"]),
  entry("\u{1F3DF}\u{FE0F}", "stadium", "Travel", ["arena", "sport"]),
  entry("\u{1F3DB}\u{FE0F}", "classical_building", "Travel", ["museum", "architecture"]),
  entry("\u{1F3D7}\u{FE0F}", "building_construction", "Travel", ["crane", "wip"]),
  entry("\u{26F2}", "fountain", "Travel", ["water", "city"]),
  entry("\u{26FA}", "tent", "Travel", ["camping"]),
  entry("\u{1F301}", "foggy", "Travel", ["weather", "mist"]),
  entry("\u{2600}\u{FE0F}", "sunny", "Travel", ["weather", "clear"]),
  entry("\u{26C5}", "rain", "Travel", ["weather", "wet"]),
  entry("\u{2744}\u{FE0F}", "snowflake", "Travel", ["weather", "cold", "winter"]),
  entry("\u{26A1}", "zap", "Travel", ["weather", "storm", "lightning"]),
  entry("\u{1F300}", "cyclone", "Travel", ["weather", "spiral"]),
  entry("\u{1F327}\u{FE0F}", "rainbow", "Travel", ["weather", "pride"]),
  entry("\u{2601}\u{FE0F}", "cloud", "Travel", ["weather"]),
  entry("\u{2B50}", "star", "Travel", ["night", "space"]),
  entry("\u{1F30C}", "milky_way", "Travel", ["space", "night"]),
  entry("\u{1F3F0}\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}", "rainbow_flag", "Travel", ["pride", "lgbtq"]),
];

/* -------------------------------- objects -------------------------------- */

const OBJECTS: EmojiEntry[] = [
  entry("\u{1F4F7}", "camera", "Objects", ["photo"]),
  entry("\u{1F528}", "hammer", "Objects", ["tool", "build"]),
  entry("\u{1FA93}", "axe", "Objects", ["tool", "chop"]),
  entry("\u{1F527}", "wrench", "Objects", ["tool", "fix"]),
  entry("\u{1F6E0}\u{FE0F}", "hammer_and_pick", "Objects", ["tools", "build"]),
  entry("\u{1F6E1}\u{FE0F}", "shield", "Objects", ["security", "protect"]),
  entry("\u{1FAA9}", "carpentry_saw", "Objects", ["tool", "cut"]),
  entry("\u{1F527}\u{FE0F}", "wrench", "Objects", ["tool"]),
  entry("\u{2699}", "gear", "Objects", ["settings", "cog"]),
  entry("\u{1F512}", "lock", "Objects", ["secure", "private"]),
  entry("\u{1F513}", "unlock", "Objects", ["open", "access"]),
  entry("\u{1F511}", "key", "Objects", ["lock", "access", "password"]),
  entry("\u{1F45D}", "bulb", "Objects", ["idea", "light"]),
  entry("\u{1F4A1}", "bulb", "Objects", ["idea", "light"]),
  entry("\u{1F526}", "flashlight", "Objects", ["torch", "light"]),
  entry("\u{1F4DA}", "books", "Objects", ["read", "library"]),
  entry("\u{1F4D6}", "open_book", "Objects", ["read", "study"]),
  entry("\u{1F4D5}", "closed_book", "Objects", ["read"]),
  entry("\u{1F4D8}", "blue_book", "Objects", ["read", "study"]),
  entry("\u{1F4D7}", "green_book", "Objects", ["read"]),
  entry("\u{1F4D9}", "notebook", "Objects", ["notes"]),
  entry("\u{1F4D3}", "notebook_with_decorative_cover", "Objects", ["notes"]),
  entry("\u{1F4F0}", "newspaper", "Objects", ["news", "press"]),
  entry("\u{1F4C1}", "file_folder", "Objects", ["folder", "files"]),
  entry("\u{1F4C2}", "open_file_folder", "Objects", ["folder"]),
  entry("\u{1F5C2}\u{FE0F}", "card_index_dividers", "Objects", ["organise"]),
  entry("\u{1F5D2}\u{FE0F}", "card_index", "Objects", ["organise"]),
  entry("\u{1F4C4}", "page_facing_up", "Objects", ["document"]),
  entry("\u{1F4B0}", "money_bag", "Objects", ["cash", "rich"]),
  entry("\u{1F4B3}", "credit_card", "Objects", ["pay", "money"]),
  entry("\u{1F48E}", "gem", "Objects", ["diamond", "jewel", " rare"]),
  entry("\u{1F4AB}", "droplet", "Objects", ["water", "liquid"]),
  entry("\u{1F9F0}", "toolbox", "Objects", ["tools", "repair"]),
  entry("\u{1F9F2}", "magnet", "Objects", ["attract"]),
  entry("\u{1FA9C}", "hook", "Objects", ["hanger"]),
  entry("\u{2692}", "scales", "Objects", ["balance", "justice"]),
  entry("\u{26CF}", "pick", "Objects", ["tool", "mine"]),
  entry("\u{1F527}\u{FE0F}\u{2692}", "toolbox", "Objects", ["tools"]),
  entry("\u{1F9F3}", "broom", "Objects", ["clean", "sweep"]),
  entry("\u{1F9FA}", "basket", "Objects", ["tidy"]),
  entry("\u{1F9FB}", "roll_of_paper", "Objects", ["toilet", "clean"]),
  entry("\u{1F6BF}", "shower", "Objects", ["bath", "wash"]),
  entry("\u{1F6C1}", "bathtub", "Objects", ["bath", "wash"]),
  entry("\u{1F6CB}\u{FE0F}", "couch_and_lamp", "Objects", ["living room"]),
  entry("\u{1F6BD}", "toilet", "Objects", ["bathroom"]),
  entry("\u{1F9F0}", "toolbox", "Objects", ["repair"]),
  entry("\u{1FAA1}", "window", "Objects", ["open", "view"]),
  entry("\u{1FA91}", "chair", "Objects", ["sit", "furniture"]),
  entry("\u{1FA91}", "chair", "Objects", ["furniture"]),
  entry("\u{1F6BD}", "bed", "Objects", ["sleep", "rest"]),
  entry("\u{1F6CF}\u{FE0F}", "pillow", "Objects", ["sleep", "comfort"]),
  entry("\u{1F6CB}\u{FE0F}", "couch", "Objects", ["lounge"]),
  entry("\u{1F5BC}\u{FE0F}", "framed_picture", "Objects", ["art", "wall"]),
  entry("\u{1F3B8}\u{FE0F}", "guitar", "Objects", ["instrument"]),
  entry("\u{1F941}", "drum", "Objects", ["instrument"]),
  entry("\u{1FA97}", "accordion", "Objects", ["instrument", "music"]),
  entry("\u{1FA95}", "banjo", "Objects", ["instrument"]),
  entry("\u{1F3BB}\u{FE0F}", "violin", "Objects", ["instrument", "music"]),
  entry("\u{1F3BC}", "musical_score", "Objects", ["music"]),
  entry("\u{1F3B7}", "saxophone", "Objects", ["instrument", "music"]),
  entry("\u{1F3BA}", "trumpet", "Objects", ["instrument", "music"]),
  entry("\u{1F3B4}", "musical_note", "Objects", ["music"]),
  entry("\u{1F3B6}", "musical_notes", "Objects", ["music"]),
  entry("\u{1F3B8}", "guitar", "Objects", ["music"]),
  entry("\u{1F9F8}", "teddy_bear", "Objects", ["toy", "cute"]),
  entry("\u{1FA85}", "pinata", "Objects", ["party", "candy"]),
  entry("\u{1F3AE}", "video_game", "Objects", ["gaming"]),
  entry("\u{1F3B2}", "game_die", "Objects", ["dice", "random"]),
  entry("\u{1FA80}", "yo_yo", "Objects", ["toy"]),
  entry("\u{1F3AF}", "bullseye", "Objects", ["target"]),
  entry("\u{1F3B1}", "boxing_glove", "Objects", ["sport"]),
  entry("\u{1F3CF}", "cricket_bat_and_ball", "Objects", ["sport"]),
  entry("\u{1F3F8}", "badminton_racquet_and_shuttlecock", "Objects", ["sport"]),
  entry("\u{1F94F}", "lacrosse", "Objects", ["sport"]),
  entry("\u{1FA8A}", "boxing_glove", "Objects", ["sport"]),
  entry("\u{1FA83}", "boomerang", "Objects", ["throw", "return"]),
  entry("\u{26F3}", "flag_in_hole", "Objects", ["golf"]),
  entry("\u{1F3CC}\u{FE0F}", "golf", "Objects", ["sport"]),
  entry("\u{1F3D3}", "ping_pong", "Objects", ["sport"]),
  entry("\u{1F94C}", "curling_stone", "Objects", ["sport"]),
  entry("\u{1F3D2}", "ice_hockey_stick_and_puck", "Objects", ["sport"]),
  entry("\u{1F94D}", "lacrosse", "Objects", ["sport"]),
  entry("\u{1F3D1}", "field_hockey_stick_and_ball", "Objects", ["sport"]),
  entry("\u{1F3C7}", "horse_racing", "Objects", ["sport"]),
  entry("\u{1F3C9}", "bowling", "Objects", ["sport"]),
  entry("\u{26BD}", "soccer", "Objects", ["sport"]),
  entry("\u{1F3C6}", "trophy", "Objects", ["win", "award"]),
  entry("\u{1F3C5}", "sports_medal", "Objects", ["award"]),
  entry("\u{26BD}\u{FE0F}", "soccer", "Objects", ["sport"]),
  entry("\u{1F9FF}", "nazar_amulet", "Objects", ["protection", "eye"]),
  entry("\u{1FAA0}", "hamsa", "Objects", ["protection"]),
  entry("\u{1F9FC}", "mirror", "Objects", ["reflect"]),
  entry("\u{1FA93}", "axe", "Objects", ["tool"]),
];

/* -------------------------------- symbols -------------------------------- */

const SYMBOLS: EmojiEntry[] = [
  entry("\u{2764}\u{FE0F}", "heart", "Symbols", ["love"]),
  entry("\u{1F494}", "broken_heart", "Symbols", ["sad"]),
  entry("\u{1F4AF}", "hundred", "Symbols", ["100"]),
  entry("\u{1F522}", "1234", "Symbols", ["numbers"]),
  entry("\u{2705}", "white_check_mark", "Symbols", ["done", "yes", "tick"]),
  entry("\u{274C}", "x", "Symbols", ["no", "wrong", "fail"]),
  entry("\u{2757}", "exclamation", "Symbols", ["!" , "important"]),
  entry("\u{2753}", "question", "Symbols", ["?"]),
  entry("\u{203C}\u{FE0F}", "bangbang", "Symbols", ["!!"]),
  entry("\u{2049}\u{FE0F}", "exclamation_question", "Symbols", ["!?"]),
  entry("\u{1F197}", "ok", "Symbols", ["yes", "agree"]),
  entry("\u{1F171}", "new", "Symbols", ["fresh", "badge"]),
  entry("\u{1F53A}", "arrow_up", "Symbols", ["direction"]),
  entry("\u{2B06}\u{FE0F}", "arrow_up", "Symbols", ["direction"]),
  entry("\u{2B07}\u{FE0F}", "arrow_down", "Symbols", ["direction"]),
  entry("\u{2B05}\u{FE0F}", "arrow_left", "Symbols", ["direction"]),
  entry("\u{27A1}\u{FE0F}", "arrow_right", "Symbols", ["direction"]),
  entry("\u{1F503}", "arrows_counterclockwise", "Symbols", ["sync", "refresh"]),
  entry("\u{1F504}", "arrows_clockwise", "Symbols", ["sync", "load"]),
  entry("\u{1F519}", "arrow_back", "Symbols", ["return", "previous"]),
  entry("\u{1F51A}", "arrow_right_hook", "Symbols", ["share"]),
  entry("\u{1F4A2}", "anger", "Symbols", ["mad"]),
  entry("\u{1F4A5}", "collision", "Symbols", ["boom", "explode"]),
  entry("\u{1F4AB}", "dizzy", "Symbols", ["star"]),
  entry("\u{1F4A6}", "droplet", "Symbols", ["water"]),
  entry("\u{1F4A8}", "dash", "Symbols", ["fast"]),
  entry("\u{1F573}\u{FE0F}", "hole", "Symbols", ["circle"]),
  entry("\u{1F4AC}", "speech_balloon", "Symbols", ["comment"]),
  entry("\u{1F5E8}\u{FE0F}", "left_speech_bubble", "Symbols", ["comment"]),
  entry("\u{1F5EF}\u{FE0F}", "right_anger_bubble", "Symbols", ["comment", "mad"]),
  entry("\u{1F4A4}", "zzz", "Symbols", ["sleep", "boring"]),
  entry("\u{1F4AC}\u{FE0F}", "speech_balloon", "Symbols", ["comment"]),
  entry("\u{1F441}\u{FE0F}", "eyes", "Symbols", ["look"]),
  entry("\u{1F440}", "eyes", "Symbols", ["look"]),
  entry("\u{231B}", "hourglass", "Symbols", ["time", "wait"]),
  entry("\u{23F3}", "hourglass_flowing_sand", "Symbols", ["time", "wait"]),
  entry("\u{23F0}", "alarm_clock", "Symbols", ["time", "alarm"]),
  entry("\u{23F1}\u{FE0F}", "stopwatch", "Symbols", ["time", "timer"]),
  entry("\u{23F2}\u{FE0F}", "timer", "Symbols", ["time"]),
  entry("\u{1F570}\u{FE0F}", "clock", "Symbols", ["time"]),
  entry("\u{1F311}", "new_moon", "Symbols", ["night", "phase"]),
  entry("\u{1F312}", "waxing_crescent_moon", "Symbols", ["night", "phase"]),
  entry("\u{1F313}", "first_quarter_moon", "Symbols", ["night", "phase"]),
  entry("\u{1F314}", "waxing_gibbous_moon", "Symbols", ["night", "phase"]),
  entry("\u{1F315}", "full_moon", "Symbols", ["night", "phase"]),
  entry("\u{1F316}", "waning_gibbous_moon", "Symbols", ["night", "phase"]),
  entry("\u{1F317}", "last_quarter_moon", "Symbols", ["night", "phase"]),
  entry("\u{1F318}", "waning_crescent_moon", "Symbols", ["night", "phase"]),
  entry("\u{1F319}", "crescent_moon", "Symbols", ["night"]),
  entry("\u{1F31A}", "new_moon_face", "Symbols", ["night"]),
  entry("\u{2B50}", "star", "Symbols", ["favourite"]),
  entry("\u{1F31F}", "star2", "Symbols", ["glow", "shine"]),
  entry("\u{1F320}", "comet", "Symbols", ["space", "shooting star"]),
  entry("\u{1F30C}", "milky_way", "Symbols", ["space"]),
  entry("\u{1F31F}\u{FE0F}", "star2", "Symbols", ["shine"]),
  entry("\u{1F52F}", "dotted_six_pointed_star", "Symbols", ["magic"]),
  entry("\u{1F4AE}", "white_flower", "Symbols", ["flower", "pure"]),
  entry("\u{1F3F5}\u{FE0F}", "rosette", "Symbols", ["flower"]),
  entry("\u{1F33F}", "herb", "Symbols", ["plant", "leaf"]),
  entry("\u{1F340}", "four_leaf_clover", "Symbols", ["luck"]),
  entry("\u{1F341}", "maple_leaf", "Symbols", ["autumn", "canada"]),
  entry("\u{1F342}", "fallen_leaf", "Symbols", ["autumn"]),
  entry("\u{1F344}", "mushroom", "Symbols", ["fungus", "nature"]),
  entry("\u{1F353}", "strawberry", "Symbols", ["fruit"]),
  entry("\u{1F33A}", "hibiscus", "Symbols", ["flower"]),
  entry("\u{1F338}", "cherry_blossom", "Symbols", ["flower", "sakura"]),
  entry("\u{1F4AE}", "flower", "Symbols", ["nature"]),
  entry("\u{1F3F3}\u{FE0F}", "white_flag", "Symbols", ["surrender"]),
  entry("\u{1F3F3}", "white_flag", "Symbols", ["surrender"]),
  entry("\u{1F3F4}\u{FE0F}", "black_flag", "Symbols", ["dark"]),
  entry("\u{1F3C1}", "chequered_flag", "Symbols", ["race", "finish"]),
  entry("\u{2696}", "scales", "Symbols", ["justice", "balance"]),
  entry("\u{269B}", "atom", "Symbols", ["science", "physics"]),
  entry("\u{1F52C}", "microscope", "Symbols", ["science", "research"]),
  entry("\u{1F52D}", "telescope", "Symbols", ["space", "stars"]),
  entry("\u{1F9E9}", "brain", "Symbols", ["smart", "think"]),
  entry("\u{1F9EA}", "test_tube", "Symbols", ["science", "lab"]),
  entry("\u{1F9EC}", "dna", "Symbols", ["biology", "genetics"]),
  entry("\u{1F52B}", "thermometer", "Symbols", ["temperature"]),
  entry("\u{1F4A1}", "light_bulb", "Symbols", ["idea"]),
  entry("\u{1F50D}", "mag", "Symbols", ["search", "find"]),
  entry("\u{1F50E}", "mag_right", "Symbols", ["search", "find"]),
  entry("\u{1F56F}", "lamp", "Symbols", ["light"]),
  entry("\u{1F3A1}", "carousel_horse", "Symbols", ["fair", "carousel"]),
  entry("\u{26A0}\u{FE0F}", "warning", "Symbols", ["caution", "alert"]),
  entry("\u{1F6AB}", "prohibited", "Symbols", ["no", "ban"]),
  entry("\u{1F6B3}", "no_bicycles", "Symbols", ["no", "ban"]),
  entry("\u{1F6AD}", "no_smoking", "Symbols", ["no", "ban"]),
  entry("\u{1F6AF}", "no_littering", "Symbols", ["no", "ban"]),
  entry("\u{1F6B1}", "non_potable_water", "Symbols", ["no", "ban"]),
  entry("\u{1F517}", "link", "Symbols", ["url", "chain"]),
  entry("\u{1F517}\u{FE0F}", "link", "Symbols", ["url"]),
  entry("\u{1F4A1}", "bulb", "Symbols", ["idea"]),
  entry("\u{1F526}", "flashlight", "Symbols", ["light"]),
  entry("\u{1F56E}", "bookmark", "Symbols", ["save"]),
  entry("\u{1F4F0}", "newspaper", "Symbols", ["news"]),
  entry("\u{1F4CC}", "memo", "Symbols", ["note"]),
  entry("\u{1F4CE}", "paperclip", "Symbols", ["attach", "file"]),
  entry("\u{2702}\u{FE0F}", "scissors", "Symbols", ["cut"]),
  entry("\u{1F5C3}\u{FE0F}", "card_file_box", "Symbols", ["archive"]),
  entry("\u{1F5D1}\u{FE0F}", "wastebasket", "Symbols", ["trash", "delete"]),
  entry("\u{2714}\u{FE0F}", "check_mark", "Symbols", ["done"]),
  entry("\u{2716}\u{FE0F}", "x_mark", "Symbols", ["no"]),
  entry("\u{27A4}\u{FE0F}", "arrow_right_hook", "Symbols", ["share"]),
  entry("\u{279C}", "arrows_counterclockwise", "Symbols", ["refresh"]),
  entry("\u{1F53B}", "arrow_down_small", "Symbols", ["direction"]),
  entry("\u{1F503}\u{FE0F}", "arrows_counterclockwise", "Symbols", ["refresh"]),
  entry("\u{1F51F}", "keycap_ten", "Symbols", ["number"]),
  entry("\u{1F520}", "input_latin_uppercase", "Symbols", ["input", "caps"]),
  entry("\u{1F521}", "input_latin_lowercase", "Symbols", ["input"]),
  entry("\u{1F522}", "input_numbers", "Symbols", ["input", "number"]),
  entry("\u{1F523}", "input_symbols", "Symbols", ["input"]),
  entry("\u{1F18E}", "ab", "Symbols", ["blood", "type"]),
  entry("\u{1F191}", "cl", "Symbols", ["clear", "type"]),
  entry("\u{1F192}", "cool", "Symbols", ["type"]),
  entry("\u{1F193}", "free", "Symbols", ["type"]),
  entry("\u{1F194}", "id", "Symbols", ["type"]),
  entry("\u{1F195}", "new2", "Symbols", ["type"]),
  entry("\u{1F196}", "ng", "Symbols", ["type"]),
  entry("\u{1F17E}\u{FE0F}", "o2", "Symbols", ["type"]),
  entry("\u{1F17F}\u{FE0F}", "ok2", "Symbols", ["type"]),
  entry("\u{1F201}", "sos", "Symbols", ["help", "emergency"]),
  entry("\u{1F202}", "up!", "Symbols", ["up"]),
  entry("\u{1F237}", "hourglass_flowing_sand", "Symbols", ["time"]),
  entry("\u{24C2}\u{FE0F}", "m", "Symbols", ["airplane", "letter"]),
  entry("\u{1F19A}", "free2", "Symbols", ["type"]),
  entry("\u{1F201}", "sos", "Symbols", ["emergency"]),
  entry("\u{1F21A}", "copyright", "Symbols", ["legal", "mark"]),
  entry("\u{1F22F}", "registered", "Symbols", ["legal", "mark"]),
  entry("\u{00A9}\u{FE0F}", "copyright", "Symbols", ["legal"]),
  entry("\u{00AE}", "registered", "Symbols", ["legal"]),
  entry("\u{303D}\u{FE0F}", "part_alternation_mark", "Symbols", ["japan"]),
  entry("\u{303E}\u{FE0F}", "conjugation", "Symbols", ["japan"]),
  entry("\u{1F250}", "bamboo", "Symbols", ["japan"]),
];

/* --------------------------------- flags --------------------------------- */

const FLAGS: EmojiEntry[] = [
  entry("\u{1F1E6}\u{1F1E7}", "flag_br", "Flags", ["brazil"]),
  entry("\u{1F1E9}\u{1F1EA}", "flag_de", "Flags", ["germany"]),
  entry("\u{1F1EB}\u{1F1F7}", "flag_fr", "Flags", ["france"]),
  entry("\u{1F1EE}\u{1F1F3}", "flag_gb", "Flags", ["uk", "britain", "england"]),
  entry("\u{1F1EA}\u{1F1FA}", "flag_es", "Flags", ["spain"]),
  entry("\u{1F1EC}\u{1F1E7}", "flag_it", "Flags", ["italy"]),
  entry("\u{1F1E7}\u{1F1F7}", "flag_jp", "Flags", ["japan"]),
  entry("\u{1F1F0}\u{1F1F7}", "flag_kr", "Flags", ["korea", "south"]),
  entry("\u{1F1F8}\u{1F1EA}", "flag_se", "Flags", ["sweden"]),
  entry("\u{1F1EA}\u{1F1F8}", "flag_es2", "Flags", ["spain"]),
  entry("\u{1F1E8}\u{1F1E6}", "flag_ca", "Flags", ["canada"]),
  entry("\u{1F1E6}\u{1F1FA}", "flag_au", "Flags", ["australia"]),
  entry("\u{1F1E6}\u{1F1FA}\u{FE0F}", "flag_au", "Flags", ["australia"]),
  entry("\u{1F1F8}\u{1F1EE}", "flag_in", "Flags", ["india"]),
  entry("\u{1F1F3}\u{1F1F1}", "flag_nl", "Flags", ["netherlands", "holland"]),
  entry("\u{1F1F5}\u{1F1ED}", "flag_pl", "Flags", ["poland"]),
  entry("\u{1F1F5}\u{1F1F1}", "flag_pt", "Flags", ["portugal"]),
  entry("\u{1F1F9}\u{1F1ED}", "flag_tr", "Flags", ["turkey"]),
  entry("\u{1F1FA}\u{1F1F8}", "flag_us", "Flags", ["usa", "america"]),
  entry("\u{1F1F8}\u{1F1FA}", "flag_us2", "Flags", ["usa"]),
  entry("\u{1F1E6}\u{1F1F7}", "flag_ar", "Flags", ["argentina"]),
  entry("\u{1F1E7}\u{1F1F7}", "flag_au2", "Flags", ["austria"]),
  entry("\u{1F1E7}\u{1F1F4}", "flag_bh", "Flags", ["bahrain"]),
  entry("\u{1F1E7}\u{1F1E9}", "flag_be", "Flags", ["belgium"]),
  entry("\u{1F1F4}\u{1F1F7}", "flag_mx", "Flags", ["mexico"]),
  entry("\u{1F1F8}\u{1F1E7}", "flag_ch", "Flags", ["switzerland"]),
  entry("\u{1F1E8}\u{1F1EF}", "flag_cz", "Flags", ["czechia"]),
  entry("\u{1F1F0}\u{1F1F7}", "flag_gr", "Flags", ["greece"]),
  entry("\u{1F1EE}\u{1F1F9}", "flag_ie", "Flags", ["ireland"]),
  entry("\u{1F1F2}\u{1F1FD}", "flag_mx2", "Flags", ["mexico"]),
  entry("\u{1F1F3}\u{1F1F4}", "flag_nz", "Flags", ["new zealand"]),
  entry("\u{1F1F5}\u{1F1F9}", "flag_ro", "Flags", ["romania"]),
  entry("\u{1F1F8}\u{1F1E6}", "flag_sa", "Flags", ["saudi arabia"]),
  entry("\u{1F1F8}\u{1F1E6}\u{FE0F}", "flag_sa", "Flags", ["saudi arabia"]),
  entry("\u{1F1EA}\u{1F1EC}", "flag_gb2", "Flags", ["britain"]),
  entry("\u{1F1F8}\u{1F1EA}", "flag_co", "Flags", ["colombia"]),
  entry("\u{1F1E6}\u{1F1F9}", "flag_be2", "Flags", ["belgium"]),
  entry("\u{1F1FA}\u{1F1F3}", "flag_vn", "Flags", ["vietnam"]),
  entry("\u{1F1E6}\u{1F1F5}", "flag_pk", "Flags", ["pakistan"]),
  entry("\u{1F1E6}\u{1F1EE}", "flag_ng", "Flags", ["nigeria"]),
  entry("\u{1F1F7}\u{1F1FE}", "flag_ru", "Flags", ["russia"]),
  entry("\u{1F1E9}\u{1F1EA}", "flag_de2", "Flags", ["germany"]),
  entry("\u{1F1E8}\u{1F1E9}", "flag_cf", "Flags", ["central african republic"]),
  entry("\u{1F1E8}\u{1F1ED}", "flag_ca2", "Flags", ["canada"]),
  entry("\u{1F1F1}\u{1F1F7}", "flag_cl", "Flags", ["chile"]),
  entry("\u{1F1E8}\u{1F1F1}", "flag_bx", "Flags", ["belgium"]),
  entry("\u{1F1F7}\u{1F1F3}", "flag_cn", "Flags", ["china"]),
  entry("\u{1F1F8}\u{1F1F8}", "flag_ac", "Flags", ["ascension island"]),
  entry("\u{1F1F7}\u{1F1F4}", "flag_cx", "Flags", ["christmas island"]),
  entry("\u{1F1E8}\u{1F1ED}\u{FE0F}", "flag_ca3", "Flags", ["canada"]),
  entry("\u{1F1E6}\u{1F1E9}", "flag_cp", "Flags", ["clipperton island"]),
  entry("\u{1F1E8}\u{1F1E6}", "flag_bq", "Flags", ["caribbean netherlands"]),
  entry("\u{1F1E7}\u{1F1FE}", "flag_by", "Flags", ["belarus"]),
  entry("\u{1F1E8}\u{1F1F3}", "flag_cv", "Flags", ["cape verde"]),
  entry("\u{1F1E8}\u{1F1FA}", "flag_cu", "Flags", ["cuba"]),
  entry("\u{1F1E8}\u{1F1EF}", "flag_ee", "Flags", ["estonia"]),
  entry("\u{1F1EC}\u{1F1ED}", "flag_kz", "Flags", ["kazakhstan"]),
  entry("\u{1F1F2}\u{1F1F6}", "flag_na", "Flags", ["namibia"]),
  entry("\u{1F1EE}\u{1F1F4}", "flag_eu", "Flags", ["european union"]),
  entry("\u{1F1F0}\u{1F1FC}", "flag_kr2", "Flags", ["south korea"]),
  entry("\u{1F1EF}\u{1F1F5}", "flag_jp2", "Flags", ["japan"]),
  entry("\u{1F1E7}\u{1F1F7}\u{FE0F}", "flag_at", "Flags", ["austria"]),
  entry("\u{1F1F2}\u{1F1F0}", "flag_cz2", "Flags", ["czechia"]),
  entry("\u{1F1F9}\u{1F1F7}", "flag_tw", "Flags", ["taiwan"]),
  entry("\u{1F1FA}\u{1F1F2}", "flag_gq", "Flags", ["equatorial guinea"]),
  entry("\u{1F1F8}\u{1F1EE}", "flag_cm", "Flags", ["cameroon"]),
  entry("\u{1F1EC}\u{1F1F7}", "flag_it2", "Flags", ["italy"]),
];

/* ---------------------------------------------------------------------- */

export const EMOJIS: EmojiEntry[] = [
  ...SMILEYS,
  ...GESTURES,
  ...PEOPLE,
  ...ANIMALS,
  ...FOOD,
  ...ACTIVITY,
  ...TRAVEL,
  ...OBJECTS,
  ...SYMBOLS,
  ...FLAGS,
];
