/**
 * Builds the body of a GitHub release.
 *
 * This is the "changelog" the release workflow publishes: every commit in the release, one per
 * line, each credited to the account that made it, an optional trailing comment, and a link back
 * to the deployed site. The link text and URL come from `DISTOOLS_CONFIG`, so a fork announces
 * itself rather than this repo.
 *
 * Configured by environment variables so it drops cleanly into a workflow:
 *
 * - `RELEASE_FROM`    — git ref to start from. Empty means the whole history.
 * - `RELEASE_COMMENT` — optional line appended after the commits.
 * - `RELEASE_OUT`     — file to write. Defaults to `release-notes.md`.
 * - `GITHUB_REPOSITORY` / `GITHUB_TOKEN` — optional; when present, commit authors are matched to
 *   GitHub accounts so the notes credit `@handle` instead of a git name.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { deployOrigin, parseDistoolsConfig } from "../src/lib/core/config";

interface Entry {
  sha: string;
  subject: string;
  name: string;
}

function git(args: string[]): string {
  return execFileSync("git", args, {
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
    // Keep git's own complaints off the console; callers decide what to do about a failure.
    stdio: ["ignore", "pipe", "ignore"],
  }).trim();
}

function readCommits(from: string): Entry[] {
  const range = from ? `${from}..HEAD` : "HEAD";

  let output: string;
  try {
    output = git(["log", range, "--no-merges", "--pretty=format:%H%x09%s%x09%an"]);
  } catch {
    // An empty repository, or a range that resolves to no commits.
    return [];
  }
  if (!output) return [];

  return output
    .split("\n")
    .map((line) => {
      const [sha, subject, name] = line.split("\t");
      return { sha, subject: subject ?? "", name: name ?? "" };
    })
    .filter((entry) => entry.sha && entry.subject)
    // Release commits are generated by this workflow, not written by a person.
    .filter((entry) => !/^chore\(release\)/i.test(entry.subject));
}

/**
 * Maps commit SHAs to GitHub logins using the API.
 *
 * Best-effort and bounded: a handful of pages, and a silent fallback to the git author name if
 * there is no token, no network, or the commit predates the API's reach.
 */
async function fetchLogins(repository: string, token: string): Promise<Map<string, string>> {
  const logins = new Map<string, string>();

  for (let page = 1; page <= 10; page += 1) {
    const url = `https://api.github.com/repos/${repository}/commits?per_page=100&page=${page}`;
    const response = await fetch(url, {
      headers: {
        Accept: "application/vnd.github+json",
        Authorization: `Bearer ${token}`,
        "User-Agent": "distools-release-notes",
      },
    });
    if (!response.ok) break;

    const list = (await response.json()) as {
      sha?: string;
      author?: { login?: string } | null;
    }[];
    if (!Array.isArray(list) || list.length === 0) break;

    for (const commit of list) {
      if (commit.sha && commit.author?.login) logins.set(commit.sha, commit.author.login);
    }
    if (list.length < 100) break;
  }

  return logins;
}

const from = (process.env.RELEASE_FROM ?? "").trim();
const comment = (process.env.RELEASE_COMMENT ?? "").trim();
const out = resolve(process.cwd(), (process.env.RELEASE_OUT ?? "release-notes.md").trim());
const repository = (process.env.GITHUB_REPOSITORY ?? "").trim();
const token = (process.env.GITHUB_TOKEN ?? "").trim();

const config = parseDistoolsConfig(readFileSync(resolve(process.cwd(), "DISTOOLS_CONFIG"), "utf8"));
const commits = readCommits(from);

const logins = repository && token ? await fetchLogins(repository, token) : new Map<string, string>();

const lines = commits.map((entry) => {
  const login = logins.get(entry.sha);
  const who = login ? `@${login}` : entry.name || "unknown";
  return `${entry.subject} (${who})`;
});

const sections = [`## CHANGELOG:`, "", lines.length > 0 ? lines.join("\n") : "No changes recorded in this release."];

if (comment) sections.push("", comment);

sections.push("", `Link to ${config.service_name}: ${deployOrigin(config.service_deploy_domain)}`);

const body = `${sections.join("\n")}\n`;
writeFileSync(out, body, "utf8");

process.stdout.write(`release notes: ${commits.length} commit(s) from ${from || "the beginning"}\n`);
process.stdout.write(`${body}\n`);
