import type { ToolDef } from "./types";
import {
  BioGenerator,
  ChannelNameGenerator,
  CustomStatus,
  DividerMaker,
  FancyText,
  MentionGenerator,
  NicknameGenerator,
  RoleNameGenerator,
  RulesGenerator,
  ServerNameGenerator,
  SmallCaps,
  SpoilerTool,
  TextTransform,
  UsernameGenerator,
  WelcomeGenerator,
  WordCounter,
  Zalgo,
} from "./text";
import {
  Base64Tool,
  ColorTool,
  JsonTool,
  MarkdownGuide,
  PasswordTool,
  TimestampTool,
  TokenInspector,
  UrlTool,
  UuidTool,
} from "./dev";
import {
  AccountAge,
  AvatarGrabber,
  BadgeChecker,
  BadgeLibrary,
  BannerGrabber,
  IdFinder,
  MessageLink,
  MockIdTool,
  ProfileViewer,
  SnowflakeTool,
} from "./ids";
import {
  InviteBuilder,
  InviteInfo,
  InviteImages,
  ServerLookup,
} from "./invite";
import {
  EmbedBuilder,
  PermissionCalculator,
  RpcPreview,
  WebhookDeleter,
  WebhookSender,
} from "./webhook";
import {
  ColorText,
  EmojiDownloader,
  EmojiLibrary,
  EmojiResizer,
  HexColorPicker,
  PfpCropper,
  RoleColorPreview,
} from "./emoji";
import {
  AgeTool,
  CountdownTool,
  DiscordSfxTool,
  SoundBoard,
  VttTool,
} from "./sound";

export const TOOLS: ToolDef[] = [
  /* ---------------------------- text & styling --------------------------- */
  {
    slug: "fancy-text",
    name: "Fancy Text",
    description: "Unicode fonts, outlines and diacritics for stylising any message.",
    category: "text",
    icon: "type",
    keywords: ["font", "unicode", "aesthetic", "bold", "italic", "outline", "fancy"],
    component: FancyText,
    featured: true,
  },
  {
    slug: "zalgo-text",
    name: "Zalgo Text",
    description: "Glitch text with combining marks, from a light touch to full meltdown.",
    category: "text",
    icon: "zap",
    keywords: ["glitch", "cursed", "combining", "weird", "chaos"],
    component: Zalgo,
  },
  {
    slug: "small-caps",
    name: "Small Caps & Script",
    description: "Small caps, superscript, subscript and other unicode case styles.",
    category: "text",
    icon: "type",
    keywords: ["smallcaps", "superscript", "subscript", "tiny", "letters"],
    component: SmallCaps,
  },
  {
    slug: "spoiler-text",
    name: "Spoiler Text",
    description: "Wrap text in Discord spoiler tags, per character or per line.",
    category: "text",
    icon: "eye",
    keywords: ["spoiler", "hide", "blur", "bars"],
    component: SpoilerTool,
  },
  {
    slug: "text-divider",
    name: "Divider Maker",
    description: "Line dividers and separators for messages, from plain rules to box art.",
    category: "text",
    icon: "grid",
    keywords: ["divider", "separator", "line", "ascii", "rule"],
    component: DividerMaker,
  },
  {
    slug: "mentions",
    name: "Mention Generator",
    description: "Build user, role, channel and everyone mentions from IDs.",
    category: "text",
    icon: "user",
    keywords: ["mention", "ping", "tag", "everyone", "role"],
    component: MentionGenerator,
    featured: true,
  },
  {
    slug: "word-counter",
    name: "Word & Character Counter",
    description: "Counts with reading time, and how much of a Discord message limit you used.",
    category: "text",
    icon: "type",
    keywords: ["count", "characters", "words", "length", "limit", "2000"],
    component: WordCounter,
  },
  {
    slug: "text-transform",
    name: "Case & Transform",
    description: "camelCase, snake_case, kebab-case, title case, reverse and more.",
    category: "text",
    icon: "wand",
    keywords: ["camelcase", "snake", "kebab", "uppercase", "title", "reverse"],
    component: TextTransform,
  },
  {
    slug: "custom-status",
    name: "Custom Status",
    description: "Status text ideas with emoji, and where to set it.",
    category: "text",
    icon: "user",
    keywords: ["status", "custom", "emoji", "nitro", "presence"],
    component: CustomStatus,
  },

  /* ------------------------------ generators ----------------------------- */
  {
    slug: "username-generator",
    name: "Username Generator",
    description: "Usernames by style: aesthetic, minimal, gamer tag, leetspeak, symbolic.",
    category: "text",
    icon: "dice",
    keywords: ["username", "name", "random", "aesthetic", "handle"],
    component: UsernameGenerator,
    featured: true,
  },
  {
    slug: "nickname-generator",
    name: "Nickname Generator",
    description: "Server nickname ideas. Anything goes up to 32 characters.",
    category: "text",
    icon: "dice",
    keywords: ["nickname", "nick", "name", "random"],
    component: NicknameGenerator,
  },
  {
    slug: "bio-generator",
    name: "Bio Generator",
    description: "Profile About Me blurbs built from real templates under 190 characters.",
    category: "text",
    icon: "user",
    keywords: ["bio", "about me", "profile", "blurb", "tagline"],
    component: BioGenerator,
  },
  {
    slug: "server-name-generator",
    name: "Server Name Generator",
    description: "Community and guild name ideas.",
    category: "text",
    icon: "users",
    keywords: ["server", "guild", "community", "name", "random"],
    component: ServerNameGenerator,
  },
  {
    slug: "channel-name-generator",
    name: "Channel Name Generator",
    description: "Coherent channel sets for a whole category, ready to paste.",
    category: "text",
    icon: "hash",
    keywords: ["channel", "name", "text", "voice", "category"],
    component: ChannelNameGenerator,
  },
  {
    slug: "role-name-generator",
    name: "Role Name & Colour Generator",
    description: "Staff role names with matching colours, ready to rebuild your role list.",
    category: "text",
    icon: "shield",
    keywords: ["role", "name", "colour", "color", "rank", "permissions"],
    component: RoleNameGenerator,
  },
  {
    slug: "rules-generator",
    name: "Server Rules Generator",
    description: "Pick the rules you want, pick a tone, get a formatted rules post.",
    category: "text",
    icon: "book",
    keywords: ["rules", "guidelines", "policy", "moderation", "post"],
    component: RulesGenerator,
    featured: true,
  },
  {
    slug: "welcome-generator",
    name: "Welcome Message Generator",
    description: "Welcome text or webhook JSON with member count and channel details.",
    category: "text",
    icon: "send",
    keywords: ["welcome", "greeting", "join", "member count", "onboarding"],
    component: WelcomeGenerator,
  },

  /* -------------------------- ids & lookups ----------------------------- */
  {
    slug: "snowflake",
    name: "Snowflake Decoder",
    description: "Turn any Discord ID into its creation date, and back again.",
    category: "ids",
    icon: "clock",
    keywords: ["snowflake", "id", "decode", "date", "timestamp", "epoch"],
    component: SnowflakeTool,
    featured: true,
  },
  {
    slug: "id-finder",
    name: "ID Finder",
    description: "Pull a snowflake out of any pasted Discord link or block of text.",
    category: "ids",
    icon: "search",
    keywords: ["find", "extract", "id", "link", "parse"],
    component: IdFinder,
  },
  {
    slug: "account-age",
    name: "Account Age Checker",
    description: "When an account was created, from its ID.",
    category: "ids",
    icon: "clock",
    keywords: ["age", "old", "new", "alt", "created", "account"],
    component: AccountAge,
    needsNetwork: true,
  },
  {
    slug: "profile-viewer",
    name: "Profile Viewer",
    description: "Avatar, banner, badges and account details for any user ID.",
    category: "ids",
    icon: "eye",
    keywords: ["profile", "lookup", "user", "info", "viewer"],
    component: ProfileViewer,
    needsNetwork: true,
    featured: true,
  },
  {
    slug: "pfp-grabber",
    name: "Avatar Grabber",
    description: "Download any user's avatar at up to 2048px, as PNG or GIF.",
    category: "ids",
    icon: "image",
    keywords: ["avatar", "pfp", "profile picture", "download", "image"],
    component: AvatarGrabber,
    needsNetwork: true,
    featured: true,
  },
  {
    slug: "banner-grabber",
    name: "Banner Grabber",
    description: "Download a user's profile banner, or their accent colour as an image.",
    category: "ids",
    icon: "image",
    keywords: ["banner", "profile", "background", "download", "accent"],
    component: BannerGrabber,
    needsNetwork: true,
  },
  {
    slug: "badge-checker",
    name: "Badge Checker",
    description: "See which Discord badges an account actually has.",
    category: "ids",
    icon: "star",
    keywords: ["badge", "hypesquad", "early supporter", "flags"],
    component: BadgeChecker,
    needsNetwork: true,
  },
  {
    slug: "badge-library",
    name: "Badge Library",
    description: "Every badge Discord has issued, what it means and how it was earned.",
    category: "ids",
    icon: "book",
    keywords: ["badge", "list", "reference", "hypesquad", "bug hunter"],
    component: BadgeLibrary,
  },
  {
    slug: "message-link",
    name: "Message Link Builder",
    description: "Build a jump link to a channel or a specific message from IDs.",
    category: "ids",
    icon: "link",
    keywords: ["message", "link", "jump", "channel", "url"],
    component: MessageLink,
  },
  {
    slug: "mock-ids",
    name: "Mock ID Generator",
    description: "Structurally valid fake snowflakes for testing parsers and databases.",
    category: "ids",
    icon: "dice",
    keywords: ["fake", "mock", "test", "seed", "dummy", "snowflake"],
    component: MockIdTool,
  },

  /* ------------------------ developer utilities -------------------------- */
  {
    slug: "json-tool",
    name: "JSON Formatter",
    description: "Pretty print, minify, sort, validate and escape JSON with error position.",
    category: "dev",
    icon: "code",
    keywords: ["json", "format", "pretty", "minify", "validate", "escape"],
    component: JsonTool,
    featured: true,
  },
  {
    slug: "base64",
    name: "Base64 Encode / Decode",
    description: "Base64 and URL-safe Base64, both directions, with UTF-8 handled.",
    category: "dev",
    icon: "code",
    keywords: ["base64", "encode", "decode", "btoa", "atob"],
    component: Base64Tool,
    featured: true,
  },
  {
    slug: "url-encoder",
    name: "URL Encode / Decode",
    description: "Percent encoding, with a table of what each special character becomes.",
    category: "dev",
    icon: "link",
    keywords: ["url", "encode", "decode", "percent", "uri", "escape"],
    component: UrlTool,
  },
  {
    slug: "uuid-generator",
    name: "UUID v4 Generator",
    description: "Cryptographically random version 4 UUIDs, in bulk.",
    category: "dev",
    icon: "hash",
    keywords: ["uuid", "guid", "random", "v4", "identifier"],
    component: UuidTool,
  },
  {
    slug: "color-converter",
    name: "Colour Converter",
    description: "Hex, RGB, HSL and decimal, with contrast checking against WCAG ratios.",
    category: "dev",
    icon: "palette",
    keywords: ["color", "colour", "hex", "rgb", "hsl", "contrast", "palette"],
    component: ColorTool,
    featured: true,
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Random passwords with a live entropy estimate. Generated locally.",
    category: "dev",
    icon: "lock",
    keywords: ["password", "random", "secure", "generator", "entropy"],
    component: PasswordTool,
    featured: true,
  },
  {
    slug: "token-inspector",
    name: "Token Inspector",
    description: "Decode a token's structure and mask it. Everything stays on your machine.",
    category: "dev",
    icon: "key",
    keywords: ["token", "decode", "inspect", "format", "mask"],
    component: TokenInspector,
  },
  {
    slug: "timestamp-generator",
    name: "Timestamp Generator",
    description: "Every Discord timestamp format from a date, plus raw Unix and ISO values.",
    category: "dev",
    icon: "clock",
    keywords: ["timestamp", "time", "unix", "iso", "relative", "epoch"],
    component: TimestampTool,
    featured: true,
  },
  {
    slug: "markdown-guide",
    name: "Markdown Guide",
    description: "Every Discord formatting trick, including the ones that are not real Markdown.",
    category: "dev",
    icon: "book",
    keywords: ["markdown", "formatting", "bold", "spoiler", "heading", "syntax"],
    component: MarkdownGuide,
  },

  /* ------------------------------- invites -------------------------------- */
  {
    slug: "invite-info",
    name: "Invite Info",
    description: "Break down a discord.gg invite: server, member counts, boosts and expiry.",
    category: "invite",
    icon: "link",
    keywords: ["invite", "server", "guild", "members", "boosts", "expires"],
    component: InviteInfo,
    needsNetwork: true,
    featured: true,
  },
  {
    slug: "invite-images",
    name: "Invite Image Grabber",
    description: "Pull the server icon, banner and splash out of any invite link.",
    category: "invite",
    icon: "image",
    keywords: ["invite", "icon", "banner", "splash", "logo", "download"],
    component: InviteImages,
    needsNetwork: true,
  },
  {
    slug: "server-lookup",
    name: "Server Lookup",
    description: "Look up a server by ID and get its icon, banner, member count and features.",
    category: "invite",
    icon: "search",
    keywords: ["server", "guild", "lookup", "id", "icon", "members"],
    component: ServerLookup,
    needsNetwork: true,
  },
  {
    slug: "invite-builder",
    name: "Invite Builder",
    description: "Build a valid invite URL with the age, use count and expiry you want.",
    category: "invite",
    icon: "wand",
    keywords: ["invite", "build", "create", "url", "expiry", "age"],
    component: InviteBuilder,
  },

  /* ------------------------------ webhooks ------------------------------- */
  {
    slug: "embed-builder",
    name: "Embed Builder",
    description: "Design an embed with the exact colours and fields, and export the payload.",
    category: "webhook",
    icon: "grid",
    keywords: ["embed", "webhook", "payload", "json", "colour", "fields"],
    component: EmbedBuilder,
    featured: true,
  },
  {
    slug: "webhook-sender",
    name: "Webhook Sender",
    description: "Post a message to your own webhook straight from the browser.",
    category: "webhook",
    icon: "send",
    keywords: ["webhook", "send", "post", "message", "notify"],
    component: WebhookSender,
    needsNetwork: true,
  },
  {
    slug: "webhook-deleter",
    name: "Webhook Deleter",
    description: "Delete a webhook you own. Needs you to type DELETE so it cannot fire by accident.",
    category: "webhook",
    icon: "trash",
    keywords: ["webhook", "delete", "remove", "cleanup"],
    component: WebhookDeleter,
    needsNetwork: true,
  },
  {
    slug: "permission-calculator",
    name: "Permission Calculator",
    description: "Work out a permission integer from tick boxes, or decode one you were given.",
    category: "webhook",
    icon: "shield",
    keywords: ["permission", "integer", "bitfield", "calculator", "bits", "manage roles"],
    component: PermissionCalculator,
  },
  {
    slug: "rpc-preview",
    name: "RPC Preview",
    description: "See how a Discord Rich Presence entry looks before you wire it up.",
    category: "webhook",
    icon: "eye",
    keywords: ["rpc", "rich presence", "activity", "preview", "presence"],
    component: RpcPreview,
  },

  /* -------------------------- emoji and images --------------------------- */
  {
    slug: "emoji-library",
    name: "Emoji Library",
    description: "Browse and copy emoji by name or category. No login, no rate limits.",
    category: "emoji",
    icon: "star",
    keywords: ["emoji", "copy", "search", "picker", "unicode"],
    component: EmojiLibrary,
    featured: true,
  },
  {
    slug: "emoji-downloader",
    name: "Emoji Downloader",
    description: "Paste an emoji link or ID and get every size, ready to save.",
    category: "emoji",
    icon: "download",
    keywords: ["emoji", "download", "png", "gif", "id", "cdn"],
    component: EmojiDownloader,
    needsNetwork: true,
  },
  {
    slug: "emoji-resizer",
    name: "Emoji Resizer",
    description: "Resize an image to Discord's emoji limits, entirely in your browser.",
    category: "emoji",
    icon: "crop",
    keywords: ["emoji", "resize", "scale", "png", "256", "upload"],
    component: EmojiResizer,
  },
  {
    slug: "pfp-cropper",
    name: "Profile Picture Cropper",
    description: "Crop an image to a Discord avatar, server icon or banner shape.",
    category: "emoji",
    icon: "scissors",
    keywords: ["pfp", "avatar", "crop", "banner", "icon", "profile picture"],
    component: PfpCropper,
  },

  /* -------------------------------- colour ------------------------------- */
  {
    slug: "hex-color-picker",
    name: "Hex Colour Picker",
    description: "Pick a hex colour and see how it reads on Discord's light and dark backgrounds.",
    category: "emoji",
    icon: "palette",
    keywords: ["hex", "colour", "color", "picker", "contrast", "readability"],
    component: HexColorPicker,
  },
  {
    slug: "role-color-preview",
    name: "Role Colour Preview",
    description: "Preview a role colour in the member list, with a contrast check.",
    category: "emoji",
    icon: "shield",
    keywords: ["role", "colour", "color", "member list", "contrast", "readability"],
    component: RoleColorPreview,
  },
  {
    slug: "color-text",
    name: "Coloured Text",
    description: "What people mean when they ask for coloured text, and what actually works.",
    category: "emoji",
    icon: "type",
    keywords: ["colour", "color", "text", "embed", "blocks", "rainbow"],
    component: ColorText,
  },

  /* ------------------------- sound and timestamps ------------------------ */
  {
    slug: "soundboard",
    name: "Sound Board",
    description: "Discord-flavoured sounds synthesised in the browser. No audio files.",
    category: "misc",
    icon: "volume",
    keywords: ["sound", "sfx", "notification", "coin", "error", "audio"],
    component: SoundBoard,
    featured: true,
  },
  {
    slug: "discord-sfx",
    name: "SFX Timeline",
    description: "Line up sounds on a timeline, play them together, export the pattern.",
    category: "misc",
    icon: "timer",
    keywords: ["sfx", "timeline", "sequence", "join", "leave", "export"],
    component: DiscordSfxTool,
  },
  {
    slug: "countdown",
    name: "Countdown",
    description: "A countdown timer with a Discord timestamp you can paste into a message.",
    category: "misc",
    icon: "clock",
    keywords: ["countdown", "timer", "event", "timestamp", "reminder"],
    component: CountdownTool,
    featured: true,
  },
  {
    slug: "vtt-tool",
    name: "VTT Reader",
    description: "Read WebVTT subtitles, list the cues and get the timings Discord expects.",
    category: "misc",
    icon: "book",
    keywords: ["vtt", "subtitles", "captions", "transcript", "timing"],
    component: VttTool,
  },
  {
    slug: "age-tool",
    name: "Age & Time Tool",
    description: "Exact age from a date, and time until a date, down to the second.",
    category: "misc",
    icon: "clock",
    keywords: ["age", "birthday", "countdown", "date", "time", "calculator"],
    component: AgeTool,
  },
];

export const TOOL_MAP = new Map(TOOLS.map((tool) => [tool.slug, tool]));